### ISSUE TITLE
Camera Movement bisher nur Parallel zur Achse

### ISSUE THREAD

**Issue by Mystler** [Bubisoft/HerrDerBloecke#3]
Bisher wird die Kamera durch direkte Übernahme der X und Y Koordinaten-Differenz des Cursors auf die Position der Kamera bewegt. Dadurch lässt sich die Kamera nur korrekt  bewegen wenn sie entlang der Y-Achse zeigt.

Sinnvoll wäre denke ich für die Kamera:
- Zoom mit Mausrad-Scroll (Plus/Minus auf Z Koordinate sollte hier reichen)
- Drehen (mit mittlerer Maustaste/Mausrad?)
- Bewegung entsprechend anpassen, also nicht X und Y Koordinate verändern, sondern entlang eines Right-Vektors verschieben.

Right-Vektor sollte sich über das Kreuzprodukt aus Vorwärts- und Up-Vektor errechnen lassen.

**Comment by Mystler** [comment]
Camera Movement ist mit 4612d08cf8b68aaf2e2ae5a0375749499fd49d65 synchron mit dem "angeklickten" Punkt in der X-Y-Ebene. Horizontale Rotation funktioniert auch schon. Bleiben nur noch evtl. vertikale Rotation und Zoom.

**Comment by ChristopherS** [comment]
Vertikale Rotation und Zoom ist auch implementiert.
