### ISSUE TITLE
Konzeption von Einheiten, Gebäuden und Ressourcen

### ISSUE THREAD

**Issue by Mystler** [Bubisoft/HerrDerBloecke#4]
Ich mach diese Issue mal auf um hier schonmal Ideen für Typen von Einheiten, Gebäuden und Ressourcen sowie nähere Informationen zu sammeln.

**Comment by Mystler** [comment]
Ich fang mal an mit ein paar Vorschlägen:

**Ressourcen**
- _Goldbarren_: Universalwährung
- _Blockterie_: Zum Bau von Gebäuden
- _Kastenbrot_: Zur Ausbildung von Einheiten

**Gebäude**:
- _Blockstatt_: Ausbildung?
- _Blockus Maximus_: Hauptgebäude?

**Einheiten**:
- _Blockutus_: Tank-Einheit mit viel HP aber wenig Angriff

**Comment by Sc0rpe** [comment]
**Gebäude**
- Blockwerk (Kraftwerk) -> generiert Blockterie
- Blockfarm / Block(bauern)hof / Kastenfarm -> generiert Kastenbrot
- Blockhütte -> Mehr Einheiten möglich, verbrauchen kontinuierlich Nahrung und generieren dafür Gold
- Blockstatt -> siehe oben
- Der Kantenlose Block ( Kugel ) / Das Relikt-> Hauptgebäude
- ( Blocklabor -> Forschung, Verbesserungen von Einheiten )
- ( Wachturm )

**Einheiten**
-  ///
-  ///
-  ///
